### ISSUE TITLE
Maven is broken?

### ISSUE THREAD

**Issue by Sollace** [MattiDragon/TlaApi#4] opened 2024-06-15 18:23 UTC
I tried adding it using jitpack as per the instructions, but it seems like it doesn't exist on there.

For now I'm just going to throw it in the lib folder, but this is something that you might want to look into.

```
A problem occurred configuring root project 'psychedelicraft'.
> Could not resolve all files for configuration ':modImplementation'.
   > Could not find com.github.mattidragon:TlaApi:1.1.0-mc.1.20.6.
     Searched in the following locations:
       - file:/home/sollace/Documents/GitRepos/minecraft_mods/Psychedelicraft/.gradle/loom-cache/remapped_mods/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
       - file:/home/sollace/.gradle/caches/fabric-loom/minecraftMaven/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
       - file:/home/sollace/Documents/GitRepos/minecraft_mods/Psychedelicraft/.gradle/loom-cache/minecraftMaven/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
       - https://maven.fabricmc.net/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
       - https://libraries.minecraft.net/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
       - https://libraries.minecraft.net/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.jar
       - https://repo.maven.apache.org/maven2/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.jar
       - https://repo.maven.apache.org/maven2/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
       - file:/home/sollace/.m2/repository/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
       - file:/home/sollace/Documents/GitRepos/minecraft_mods/Psychedelicraft/lib/TlaApi-1.1.0-mc.1.20.6.jar
       - file:/home/sollace/Documents/GitRepos/minecraft_mods/Psychedelicraft/lib/TlaApi.jar
       - https://maven.terraformersmc.com/releases/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
       - https://repo.minelittlepony-mod.com/maven/snapshot/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
       - https://repo.minelittlepony-mod.com/maven/release/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
       - https://maven.terraformersmc.com/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
       - https://jitpack.io/com/github/mattidragon/TlaApi/1.1.0-mc.1.20.6/TlaApi-1.1.0-mc.1.20.6.pom
     Required by:
         project :
```

**Comment by MattiDragon** [comment] 2024-06-16 12:41
This is is caused by the jitpack config not being set correctly for 1.21. It's still using java 18. I'll try to get a fix out soon.

**Comment by MattiDragon** [comment] 2024-06-16 12:46
Should be fixed in v1.1.1. It might take a while to show up on jitpack.

**Comment by Sollace** [comment] 2024-06-16 13:02
Woo! Thanks.

Although I wasn't trying to grab the 1.21 version. This was for 1.20.6. A 1.21 update is perfect for what I need though, so thank you tons ❤️

**Comment by Sollace** [comment] 2024-06-16 16:26
The build may still be broken for 1.1.1. I see this in the logs when I check jitpack:

```
> Task :publishMavenJavaPublicationToMavenLocal FAILED
14 actionable tasks: 14 executed
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8 -Dhttps.protocols=TLSv1.2
Note: /home/jitpack/build/implSrc/rei/java/io/github/mattidragon/tlaapi/impl/rei/TlaApiReiPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishMavenJavaPublicationToMavenLocal'.
> Failed to publish publication 'mavenJava' to repository 'mavenLocal'
   > Invalid publication 'mavenJava': multiple artifacts with the identical extension and classifier ('jar', 'sources').
```

**Comment by MattiDragon** [comment] 2024-06-16 17:08
Yeah, seems like a deeper issue with the gradle setup. I can't fix this from the phone so it'll be a few days before I can get to it.

**Closed as completed** 2024-06-23 19:15 UTC
